package tn.intervent360.intervent360.domain.model.equipment;

public enum EquipmentType {
    STREET_LIGHT ,
    TRAFFIC_LIGHT,
    LED_PANEL,
    FIRE_HYDRANT,
    WATER_PIPE,
    WATER_METER,
    PUMP_STATION ,
    SEWER_MANHOLE,
    CCTV_CAMERA ,
    IOT_SENSOR,
    BUS_STOP,
    ROAD_SECTION,
    SIDEWALK ,
    FIBER_OPTIC,
    ELECTRIC_TRANSFORMER,
    ROAD_SIGN,
    ELECTRIC_PYLON,
    WATER_TREATMENT_STATION,
    WASTE_COLLECTION_ZONE,
    PEDESTRIAN_LIGHT
}
