spring.application.name=intervent360
# ================================
# = SERVER CONFIGURATION
# ================================
server.port=8080

# ================================
# = MONGODB CONFIGURATION
# ================================
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=intervent360
spring.data.mongodb.auto-index-creation=true